[build]
  functions = "netlify/functions"
  command = """
    curl -sSL https://install.python-poetry.org | python3 - &&
    export PATH="$HOME/.local/bin:$PATH" &&
    poetry config virtualenvs.create false &&
    poetry install --no-dev &&
    poetry export -f requirements.txt --without-hashes -o requirements.txt &&
    pip install -r requirements.txt -t netlify/functions &&
    echo 'Build completed'
  """
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main"
  status = 200
